name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/banco-banquito/web-personas-frontend:latest
          build-args: |
            VITE_PARTY_API_BASE_URL=http://${{ secrets.VM_PUBLIC_IP }}:8083
            VITE_ACCOUNT_API_BASE_URL=http://${{ secrets.VM_PUBLIC_IP }}:8081/api/v2
            VITE_SWITCH_API_BASE_URL=http://${{ secrets.VM_PUBLIC_IP }}:8010
